Update the "more verbose" tutorial example
Herb-AI/Herb.jl pull request #112
Opened 2024-10-18 18:14 UTC by llewelld

There are two changes here, one of which may be a bit contentious. I really enjoyed working through this, but I was thrown by the final comments concerning 167. What's so different about 167 compared to 168? I found the program generator was quite happy to come up with a program for both.

I thought it might be interesting therefore if the 167 example was something that the program generator was not able to solve. This, I think, makes it more interesting and also emphasises that the software is doing what the user would expect (i.e. not coming up with a solution that doesn't exist).

This change therefore constrains the values to being even, so that the 167 result can't be obtained.

The second, smaller change, is to use 'Number' instead of 'Real'. I was uncomfortable with the latter simply because, even in the original version, they are in fact all integers.

I understand if you feel these changes are making things overly complicated. I just thought they'd make an interesting example.

2024-10-18 18:14 UTC, llewelld commented
@pwochner, for your consideration.

2024-10-29 13:13 UTC, pwochner requested changes
The modified example is good. Thanks for checking it so carefully. The only thing to change would be that there is two variables called `flag`. They should be unique variable names, since Pluto notebooks otherwise don't run and the CI fails.

2024-10-29 13:13 UTC, pwochner commented on docs/src/tutorials/getting_started_with_herb.jl
> +    expr_2, flag = HerbSearch.synth(problem_2, iterator_2)
Could you make sure that you use unique variable names? The Pluto notebook fails otherwise.

2024-10-29 13:13 UTC, pwochner commented on docs/src/tutorials/getting_started_with_herb.jl
> +    expr_3, flag = HerbSearch.synth(problem_3, iterator_2)
See comment above.

2024-10-31 10:18 UTC, pwochner approved these changes

2024-10-31 10:19 UTC, merged